# Generated by Django 5.2 on 2025-04-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='links',
            field=models.CharField(blank=True, help_text='e.g. LinkedIn, GitHub URLs', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
    ]
