# Generated by Django 5.2 on 2025-04-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='candidates.candidate'),
        ),
    ]
