# Generated by Django 5.2 on 2025-04-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_favorite_alter_favorite_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='favorite',
        ),
    ]
