# Generated by Django 5.2 on 2025-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_profile_is_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='top_skills',
            field=models.CharField(blank=True, help_text='Write top skills separated by commas (e.g. Communication, Leadership, SQL)'),
        ),
    ]
